[project]
name = "derisk-app"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "csunny", email = "cfqcsunny@gmail.com" }
]
license = "MIT"
readme = "README.md"
requires-python = ">= 3.10"

dependencies = [
    "derisk",
    "derisk-ext",
    "derisk-serve",
    "derisk-client",
    "aiofiles",
    "pyparsing",
]

[project.urls]
Homepage = "https://github.com/derisk-ai/DERISK"
Documentation = "http://docs.derisk.cn/docs/overview"
Repository = "https://github.com/derisk-ai/DERISK.git"
Issues = "https://github.com/derisk-ai/DERISK/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
cache = [
    "rocksdict",
]
observability = [
    "opentelemetry-api",
    "opentelemetry-sdk",
    "opentelemetry-exporter-otlp",
]
base = [
    "derisk[client,cli,agent,simple_framework,framework,code]"
]
derisks = [
    # For build derisks apps, we will be removed in the future.
    "build",
    "poetry"
]

[tool.uv]
managed = true
dev-dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/derisk_app"]
exclude = [
    "src/derisk_app/**/tests",
    "src/derisk_app/**/tests/*",
    "src/derisk_app/tests",
    "src/derisk_app/tests/*",
    "src/derisk_app/**/examples",
    "src/derisk_app/**/examples/*"
]

